INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('GLUCOSE / DEXTROSE MONOHYDRATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('GLUCOSE WITH SODIUM CHLORIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ORAL REHYDRATION SALTS',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('POTASSIUM CHLORIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SODIUM CHLORIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SODIUM HYDROGEN CARBONATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SODIUM LACTATE COMPOUND',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ZINC SULFATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ABACAVIR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ABACAVIR + LAMIVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ABACAVIR + LAMIVUDINE + ZIDOVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ATAZANAVIR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('DIDANOSINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('EFAVIRENZ',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('EFAVIRENZ + EMTRICITABINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('EMTRICITABINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LAMIVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LAMIVUDINE + NEVIRAPINE + STAVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LAMIVUDINE + NEVIRAPINE + ZIDOVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LAMIVUDINE + STAVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LAMIVUDINE + ZIDOVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LOPINAVIR + RITONAVIR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('NEVIRAPINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('RITONAVIR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SAQUINAVIR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('STAVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ZIDOVUDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ARTEMETHER',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ARTEMETHER + LUMEFANTRINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ARTESUNATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ARTESUNATE + AMODIAQUINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ARTESUNATE + MEFLOQUINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ARTESUNATE + SULFADOXINE-PYRIMETHAMINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CHLOROQUINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PRIMAQUINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PROGUANIL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('QUININE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SULFADOXINE + PYRIMETHAMINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('AMPICILLIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CAFFEINE CITRATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CEFOTAXIME',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CEFTRIAXONE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CLOXACILLIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('FLUCLOXACILLIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('GENTAMYCIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PHENOBARBITAL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PHYTOMENADIONE / VITAMIN K',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PROSTAGLANDIN E',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SURFACTANT',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('TETRACYCLINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BENZNIDAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CLOFAZIMINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('DAPSONE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('DILOXANIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('EFLORNITHINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('MELARSOPROL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('NIFURTIMOX',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PAROMOMYCIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PENTAMIDINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('RIBAVIRIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SODIUM STIBOGLUCONATE OR MEGLUMINE ANTIMONIATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SURAMIN SODIUM',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('F-75 THERAPEUTIC DIET',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('F-100 THERAPEUTIC DIET',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('READY TO USE THERAPEUTIC FOOD / RUTF',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ALFACALCIDOL / 1α-HYDROXYCHOLECALCIFEROL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ASCORBIC ACID / VITAMIN C',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CHOLECALCIFEROL / VITAMIN D3',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('FERROUS SALT',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('FOLIC ACID',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('HYDROXOCOBALAMINE / VITAMIN B12',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('IODATE SALT MIXTURE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('IODINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('MICRONUTRIENT TABLETS',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('MUTIPLE MICRONUTRIENT POWDER',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PYRIDOXINE / VITAMIN B6',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('RETINOL / VITAMIN E',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('RIBOFLAVIN / VITAMIN B2',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SODIUM FLUORIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('THIAMINE / VITAMIN B1',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ACETIC ACID',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ACICLOVIR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('ALBENDAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('AMPHOTERICIN B',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('AZITHROMYCIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BENZATHINE BENZYLPENICILLINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BENZOIC ACID + SALICYLIC ACID',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BENZOYL PEROXIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BENZYL BENZOATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BETAMETHASONE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('BLEOMYCIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CALAMINE LOTION',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CEFALEXIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CEFAZOLIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CEFIXIME',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CEFTAZIDIME',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CHLORAMPHENICOL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CHLORPHENAMINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CIPROFLOXACIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('CLINDAMYCIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('COAL TAR',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('DIETHYLCARBAMAZINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('DOXICYCLINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('FLUCONAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('FLUCYTOSINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('GRISEOFULVIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('HYDROCORTISONE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('IMIPENEM + CILASTATIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('IVERMECTIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('LEVAMISOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('MEBENDAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('METHYLROSANILINIUM CHLORIDE / GENTIAN VIOLET',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('METRONIDAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('MICONAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('NEOMYCIN SULFATE + BACITRACIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('NICLOSAMIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('NITROFURANTOIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('NYSTATIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('OXAMNIQUINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PERMETHRIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PHENOXYMETHYLPENICILLIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PODOPHYLLUM RESIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('POTASSIUM IODIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('POTASSIUM PERMANGANATE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PRAZIQUANTEL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PROCAINE BENZYLPENICILLINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PYRANTEL',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('PYRIMETHAMINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SALICYLIC ACID',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SELENIUM SULFIDE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SILVER SULFADIAZINE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('SULFAMETHOXAZOLE + TRIMETHOPRIM / COTRIMOXAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('TRICLABENDAZOLE',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('TRIMETHOPRIM',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('UREA',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('VANCOMYCIN',10)
INSERT INTO [UnicefVirtualWarehouse.UnicefContext].[dbo].[Products] ([Name],[ProductCategory_Id]) VALUES ('VINCRISTINE',10)
GO
